### ISSUE TITLE
Bundle `awesome-ci` with each PHP|HHVM Docker Container

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#109]
**[awesome-ci](https://github.com/cytopia/awesome-ci)** contains various source code analyzers and linters as well as being able to fix problems directly inside your files.

It will be good to have them integrated, so that they don't have to be installed on the host system itself.

#### TODO:

* [x] Add to Docker container
* [x] Add dependencies to Docker container
* [x] Add documentation for how to use it

**Comment by cytopia** [comment]
# Docker

* [X] https://github.com/cytopia/docker-php-fpm-5.4/pull/27

**Comment by cytopia** [comment]
merged
