### ISSUE TITLE
Move documentation to readthedocs.org

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#157]
As this projects advances it must be taken care of proper documentation that is easy to maintain, easy to add and also searchable.

The best candidate for this seems to be: **https://readthedocs.org/**

* Namespace: http://devilbox.readthedocs.io/en/latest/

## Where to preview:

http://devilbox.readthedocs.io/en/documentation/

---

This is going to take some time as I am not yet experienced with this service, so If anyone wants to join and help to port the documentation, please leave a comment below.

---

## Todo:

1. [x] Lift and shift: Make documentation as it is work with readthedocs
2. [x] Restructure documentation
3. [x] Add info about how to customize vhosts
4. [x] Add step-by-step tutorials

**Comment by panigrc** [comment]
Tempting ...
I could help you with that, to start with you probably need a Read The Docs Account and a Devilbox Docs repo. As I read you attach your github repo to your Read The Docs account and it can automatically update from the master branch.
Make it empty, and I could start porting things, by sending pull requests. Or add me as a collaborator.
My time is limited so don't expect to port this in a few days.

**Comment by panigrc** [comment]
mmm I've checked other documentations and I noticed that the others do it also like this. They place the docs directory within their project repository.
So yeah you can do it like so.
I've registered on Read The Docs but I didn't find this setting, probably because I need to create a repo in github first with docs directory in it.

**Comment by cytopia** [comment]
This might be achievable via the python configuration file. See here

![screenshot 2018-01-30 15-09-26 selection](https://user-images.githubusercontent.com/12533999/35570483-a0c14efe-05cf-11e8-8ca9-59e69e531a21.png)

**Comment by panigrc** [comment]
Oh ! nice 😄 
Now how is it possible to collaborate to the docs directory ?
Also because Read The Docs will compile the docs, means that we are going to work without a preview ? 
Forgive me about my questions but I haven't yet worked with the online service of Read the Docs

**Comment by cytopia** [comment]
@panigrc readthedocs will auto-compile each branch automatically. So I guess the best way would be:

1. I will create a long-living feature branch with an PR to master (that will stay WIP until fully done).
2. PR's will be created to go into that feature branch.
3. Documentation can then always be seen from that feature branch. `[1]`
4. Once the feature branch is in a useable state (first iteration: lift and shift), it will be merged into master.

`[1]:` Documentation is created for each repository branch and can be seen here: https://readthedocs.org/projects/devilbox/

**Comment by cytopia** [comment]
Feature branch and PR ready:

* branch: `documentation`
* PR: https://github.com/cytopia/devilbox/pull/186

**Comment by cytopia** [comment]
FYI: setup is now working as expected and I already started porting the documentation: http://devilbox.readthedocs.io/en/documentation/

**Comment by cytopia** [comment]
Resolved
