### ISSUE TITLE
https support on Devilbox

### ISSUE THREAD

**Issue by sebastienserre** [cytopia/devilbox#173]
Hello,
Is it possible to have a self signed SSL to run an https on Devilbox?
If right, then is there any tutorial somewhere ?

**Comment by cytopia** [comment]
@sebastienserre not at the moment. SSL support is coming in the first quarter of this year.

**Comment by aditya43** [comment]
Thanks for the great work. 

Please add SSL support as soon as possible. It would be great if you could also add some [devilish commands to automate most of the process](https://gist.github.com/jchandra74/36d5f8d0e11960dd8f80260801109ab0) for creating self signed certificates for local development.purposes. 

Cheers!

**Comment by johnwbaxter** [comment]
I would love to see this added too. Again, moving from a different setup where i have SSL for a lot of projects so to be able to use this would need https! Thanks!!

**Comment by cytopia** [comment]
Is it generally possible to have a wildcard certificate for a e.g. `*.dev` or does it only work with domains?

**Comment by johnwbaxter** [comment]
As far as i'm aware, browsers wont trust a certificate that covers a whole TLD so pretty sure that wouldn't work. It would have to be per domain *.project1.loc

**Comment by cytopia** [comment]
Then I guess certificates will have to be created for each available project on startup (or at least check if the currently available cert [if any] matches the current chosen TLD_SUFFIX).

**Comment by johnwbaxter** [comment]
I would say that is your only option, yes.

**Comment by johnwbaxter** [comment]
Hi! Do you have ETA on this one at all?

**Comment by cytopia** [comment]
There is actually and I wanted to have it implemented by know, however I am still working on the documentation which took a little longer than expected.
This is scheduled when the documentation is finished: https://github.com/cytopia/devilbox/pull/186

**Comment by johnwbaxter** [comment]
So awesome. Thanks!! :)

**Comment by yannandco** [comment]
Ooooh yes please! Ssl would be an awesome feature to add! 
Thx for the great work!

**Comment by cytopia** [comment]
@sebastienserre @aditya43 @johnwbaxter @yannandco @henscu @masiorama @alexagui @mrpsiho @mcliment

#### FYI: Work on HTTPS integration has been started already. See below for Roadmap and progress.

----

### Roadmap

1. [X] Implement SSL in vhost-gen: https://github.com/devilbox/vhost-gen/pull/24
2. [ ] Implement SSL in Nginx stable: currently WIP
3. [ ] Implement SSL in Nginx mainline:
4. [ ] Implement SSL in Apache 2.2:
5. [ ] Implement SSL in Apache 2.4:
6. [ ] Implement SSL in Devilbox

### Features

* Vhosts are available by http and https
* Self-signed certificates are created automatically for each vhost
* Be able to use your own certificates as well

### Comments

Let me know of any features or ideas.

### ETA

There will be a WIP branch probably by the end of this week for at least one webserver

**Comment by cytopia** [comment]
I will create a CA, that is mounted to the Devilbox git directory and only created if it is not present (should not overwrite an existing CA). All subsequent vhost SSL certificates are signed by that CA. This allows you to import the mounted CA file into Chrome/FF/IE and regardless of Devilbox restarts or recreation of site certificates, you will always get a valid certificate for each project.

**Comment by cytopia** [comment]
First working version for `nginx-stable` is ready to check out. Instructions in PR: https://github.com/cytopia/devilbox/pull/239

**Comment by cytopia** [comment]
I have created two scripts to easily generate CA's and certificates for SSL. If anyone here has some OpenSSL knowledge, please have a brief look and let me know if this is fine or needs some adjustments: https://github.com/devilbox/cert-gen

**Comment by cytopia** [comment]
## Done

Looks like it is finished now. Only part that is missing is the documentation. Check out the PR and let me know how it works for you:

https://github.com/cytopia/devilbox/pull/239

**Comment by cytopia** [comment]
Released
