### ISSUE TITLE
Failed to start on macOS

### ISSUE THREAD

**Issue by uonick** [cytopia/devilbox#50]
If you encounter a bug and something does not work, make sure you have done the following and check those boxes before submitting an issue - thank you!

- [x] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`) before running `docker-compose up`
- [x] Specify used docker versions (php, web and database)
- [ ] Attach logs for php, mysql and webserver (found in `log/` directory)
- [ ] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`)
- [x] Never use different mysql|mariadb versions on the same `HOST_PATH_TO_MYSQL_DATADIR` on existing database files. Different mysql|mariadb versions might upgrade/corrupt existing database files. If you have done that already, start with a different path of `HOST_PATH_TO_MYSQL_DATADIR` (to an empty directory) and try again.

Please also specify the following info:

- [ macOS] Which operating system are you at (Linux, OSX or Windows)
- [17.03.1-ce ] `docker version`
- [1.11.2, build dfed245] `docker-compose version`

Start log:
```
WARNING: The POSTGRES_SERVER variable is not set. Defaulting to a blank string.
Pulling postgres (postgres:latest)...
latest: Pulling from library/postgres
Digest: sha256:3b51a72ca2642f24fa782c2fb99ddb0d29cbcd38f32639c98a80966a25ae2a64
Status: Image is up to date for postgres:latest
Starting devilbox_mysql_1
Pulling postgres (postgres:latest)...
latest: Pulling from library/postgres
Digest: sha256:3b51a72ca2642f24fa782c2fb99ddb0d29cbcd38f32639c98a80966a25ae2a64
Status: Image is up to date for postgres:latest

ERROR: for postgres  Image 'postgres:' not found
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 64, in main
  File "compose/cli/main.py", line 116, in perform_command
  File "compose/cli/main.py", line 876, in up
  File "compose/project.py", line 416, in up
  File "compose/parallel.py", line 66, in parallel_execute
compose.service.NoSuchImageError: Image 'postgres:' not found
Failed to execute script docker-compose
```

`.env` file:
```
###
###  ---------------------------------------------------
###  D E V I L B O X   R U N - T I M E   S E T T I N G S
###  ---------------------------------------------------
###
###  All the following settings are applied during
###  $ docker-compose up
###
###  No need to rebuild any dockers!
###

###
### Show all executed commands in each
### docker image during docker-compose up?
###
### 1: Yes
### 0: No
DEBUG_COMPOSE_ENTRYPOINT=1



###
### Relative or absolute path to the devilbox repository.
### (Used as a prefix for all mount paths)
### There is no need to change this.
###
### The only exception is for OSX users wanting to use NFS
### mounts instead of Filesystem mounts due to degraded performance
### on OSX.
###
DEVILBOX_PATH=.


###
### At what IP address should the docker services listen
### on the Host computer?
###
### The specified default should be fine for Linux and OSX (127.0.0.1:).
### If you are on windows, you will probably have to change
### it to the IP address of the docker machine.
###
### a.) Leave blank, to listen on all interfaces (no trailing color ':')
###    LOCAL_LISTEN_ADDR=
### b.) If an IP is specified, note the trailing colon ':'
###    LOCAL_LISTEN_ADDR=127.0.0.1:
###
LOCAL_LISTEN_ADDR=127.0.0.1:


################################################################################
###
### 1. Choose Images (Version)
###
################################################################################

###
### You can choose any combination of httpd, mysql, postgresql or php.
### Each of them are fully compatible between one another.
###


###
### 1.1 Choose HTTP Server Image
###
#HTTPD_SERVER=apache-2.2
#HTTPD_SERVER=apache-2.4
HTTPD_SERVER=nginx-stable
#HTTPD_SERVER=nginx-mainline

###
### 1.2 Choose MySQL Server Image
###
#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
#MYSQL_SERVER=mysql-5.7
MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=mariadb-5.5
#MYSQL_SERVER=mariadb-10.0
#MYSQL_SERVER=mariadb-10.1
#MYSQL_SERVER=mariadb-10.2
#MYSQL_SERVER=mariadb-10.3

###
### 1.3 Choose PostgreSQL Server Image
###
#POSTGRES_SERVER=9.1
#POSTGRES_SERVER=9.2
#POSTGRES_SERVER=9.3
#POSTGRES_SERVER=9.4
#POSTGRES_SERVER=9.5
#POSTGRES_SERVER=9.6

###
### 1.4 Choose PHP Server Image
###
#PHP_SERVER=php-fpm-5.4
#PHP_SERVER=php-fpm-5.5
#PHP_SERVER=php-fpm-5.6
#PHP_SERVER=php-fpm-7.0
PHP_SERVER=php-fpm-7.1
#PHP_SERVER=hhvm-latest


###
### 1.5 Choose Redis Server Image
###     (only for docker-compose.optional.yml)
###     $ docker-compose -f docker-compose.optional.yml up
###
#REDIS_SERVER=2.8
#REDIS_SERVER=3.0
REDIS_SERVER=3.2


###
### 1.6 Timezone for all dockers and service config files
###
TIMEZONE=Europe/Moscow



################################################################################
###
### 2. Host Mounts (Your computer)
###
################################################################################

###
### Local filesystem path to www projects.
###
HOST_PATH_TO_WWW_DOCROOTS=~/Projects/

###
### Local filesystem path to mysql/mariadb datadir.
###
### This can be an existing mysql data directory or empty.
### If it already is a mysql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new mysql database will be
### created.
###
### Note: Inside this path, a subdirectory with the mysql|mariadb
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older mysql|mariadb server versions.
###
HOST_PATH_TO_MYSQL_DATADIR=/Users/uonick/mysql80

###
### Local filesystem path to postgresql datadir.
###
### This can be an existing postgresql data directory or empty.
### If it already is a postgresql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new postgresql database will be
### created.
###
### Note: Inside this path, a subdirectory with the postgresql
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older postgres server versions.
HOST_PATH_TO_POSTGRES_DATADIR=./data/pgsql



################################################################################
###
### 3. HTTP Docker Settings
###
################################################################################

###
### Expose HTTPD Port to Host
###
HOST_PORT_HTTPD=80


################################################################################
###
### 4. MySQL Docker Settings
###
################################################################################

###
### MySQL root user password
###
### If $HOST_PATH_TO_MYSQL_DATADIR already contains an existing
### mysql datadir, enter the password for the existing mysql database
###
### If $HOST_PATH_TO_MYSQL_DATADIR is empty, choose a new password that
### will be applied
###
MYSQL_ROOT_PASSWORD=

###
### Custom MySQL Runtime Settings
###
MYSQL_GENERAL_LOG=1

###
### Expose MySQL Port to Host
###
HOST_PORT_MYSQL=3306



################################################################################
###
### 5. PostgreSQL Docker Settings
###
################################################################################

###
### PostgreSQL 'root' user name (usually postgres)
###
POSTGRES_USER=postgres

###
### PostgreSQL 'root' user password
###
POSTGRES_PASSWORD=

###
### Expose MySQL Port to Host
###
HOST_PORT_POSTGRES=5432


################################################################################
###
### 6. PHP-FPM Docker Settings
###
################################################################################

###
### Xdebug
###

# Enable/Disable Xdebug
PHP_XDEBUG_ENABLE=0

# Your local port (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_PORT=9000

# Your local IP address (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_HOST=172.20.10.2
## TODO: Check if it works by automatically sending it to the broadcast address



################################################################################
###
### 7. Redis Docker Settings
###
################################################################################

###
### Expost Redis Port to Host
###
HOST_PORT_REDIS=6379

```

I disabled postgres why does it want to run? 😕

**Comment by cytopia** [comment]
Hi @uonick ,

It is currently (due to docker-compose limitations) not possible to optionally start containers within a compose file. So for now there are two compose files:

1. docker-compose.yml
2. docker-compose.optional.yml

The first one will/must start: php, httpd, mysql and postgresql
The second one will/must start all of the above plus redis.

So you will have to uncomment redis.

FYI: This has already been requested here: https://github.com/cytopia/devilbox/issues/31

However I still have no idea how to implement it.

**Comment by uonick** [comment]
@cytopia thanks for the explanation 😯

**Comment by cytopia** [comment]
@uonick Does it work on OSX once you re-enable postfix?

**Comment by uonick** [comment]
Nope =( the same error after 4 restarts. Returned to vagrant.

**Comment by cytopia** [comment]
@uonick problems should be resolved with the new release.

I will close this issue. In case you might drop by and still experience problems, just re-open it.

**Comment by uonick** [comment]
@cytopia thnx for the ur great work! but:
```
uonick ~/Projects/devilbox $ docker-compose up
Starting devilbox_bind_1

ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (68d2ca4729d7c8e480d3942f9d86292d8351bf931d1d5fc1b85ce1c9f3b867ff): Error starting userland proxy: Bind for 127.0.0.1:53: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
```

**Comment by cytopia** [comment]
Hey @uonick :

`(Failure EADDRINUSE)` This is because you already have a local DNS resolver running on port 53 at least on localhost.

You either have to disable it or change the devilbox's DNS listening port in the `.env` file: `HOST_PORT_BIND=53` to `54`

However, when you use the devilbox's DNS server (which requires an entry in your `/etc/resolv.conf`), custom domains will always work automatically (whatever you set in the `TLD_SUFFIX` does not need to be added to your `/etc/hosts`)

Example:

You have `TLD_SUFFIX=local` and added a project folder: `my-wordpress`. Then you normally have to create an entry in `/etc/hosts` like so;
```
127.0.0.1 my-wordpress.local
```

When you do use the devilbox DNS resolver, this DNS entry automatically exists

**Comment by cytopia** [comment]
See here for how to add the devilbox's DNS resolver: https://github.com/cytopia/devilbox/issues/63
