### ISSUE TITLE
Not working after update to 0.9

### ISSUE THREAD

**Issue by fe3dback** [cytopia/devilbox#61]
All working, its my mistake. see comment
----

After update to 0.9, "docker-compose up" won't work anymore.

```
$ docker-compose up
WARNING: The PGSQL_ROOT_USER variable is not set. Defaulting to a blank string.
WARNING: The PGSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The PGSQL_SERVER variable is not set. Defaulting to a blank string.
WARNING: The HOST_PATH_PGSQL_DATADIR variable is not set. Defaulting to a blank string.
WARNING: The HOST_PORT_PGSQL variable is not set. Defaulting to a blank string.
WARNING: The HOST_PATH_HTTPD_DATADIR variable is not set. Defaulting to a blank string.
WARNING: The HOST_PORT_MEMCD variable is not set. Defaulting to a blank string.
WARNING: The MEMCD_SERVER variable is not set. Defaulting to a blank string.
WARNING: The HOST_PORT_BIND variable is not set. Defaulting to a blank string.
WARNING: The HOST_PATH_MYSQL_DATADIR variable is not set. Defaulting to a blank string.
Creating network "devilbox_app_net" with driver "bridge"
Creating devilbox_bind_1 ... 
Creating devilbox_bind_1 ... done
Creating devilbox_php_1 ... 
Creating devilbox_php_1 ... error

ERROR: for devilbox_php_1  Cannot create container for service php: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for php  Cannot create container for service php: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

---
- [x] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`)
cytopia/mysql-5.7      0.9                 5c982535f75d        25 hours ago        1.28 GB
cytopia/php-fpm-7.0    0.9                 82ba5f8da78c        25 hours ago        605 MB
cytopia/apache-2.4     0.9                 c603d612adb4        25 hours ago        365 MB
cytopia/mysql-5.7      latest              5dd6c258b463        27 hours ago        1.28 GB
cytopia/apache-2.4     latest              bc2a2d3ea891        27 hours ago        365 MB
cytopia/php-fpm-7.0    latest              3813610ad2ee        28 hours ago        605 MB

- [x] Which operating system are you at (Linux, OSX or Windows)
```
Linux more 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- [x] `docker version`
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
- [x] `docker-compose version`
```
docker-compose version 1.13.0-rc1, build 38af513
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

My .env file:
```
###
###  ---------------------------------------------------
###  D E V I L B O X   R U N - T I M E   S E T T I N G S
###  ---------------------------------------------------
###
###  All the following settings are applied during
###  $ docker-compose up
###
###  No need to rebuild any dockers!
###

###
### Show all executed commands in each
### docker image during docker-compose up?
###
### 1: Yes
### 0: No
DEBUG_COMPOSE_ENTRYPOINT=1



###
### Relative or absolute path to the devilbox repository.
### (Used as a prefix for all mount paths)
### There is no need to change this.
###
### The only exception is for OSX users wanting to use NFS
### mounts instead of Filesystem mounts due to degraded performance
### on OSX.
###
DEVILBOX_PATH=.


###
### At what IP address should the docker services listen
### on the Host computer?
###
### The specified default should be fine for Linux and OSX (127.0.0.1:).
### If you are on windows, you will probably have to change
### it to the IP address of the docker machine.
###
### a.) Leave blank, to listen on all interfaces (no trailing color ':')
###    LOCAL_LISTEN_ADDR=
### b.) If an IP is specified, note the trailing colon ':'
###    LOCAL_LISTEN_ADDR=127.0.0.1:
###
LOCAL_LISTEN_ADDR=127.0.0.1:


################################################################################
###
### 1. Choose Images (Version)
###
################################################################################

###
### You can choose any combination of httpd, mysql, postgresql or php.
### Each of them are fully compatible between one another.
###


###
### 1.1 Choose HTTP Server Image
###
#HTTPD_SERVER=apache-2.2
HTTPD_SERVER=apache-2.4
#HTTPD_SERVER=nginx-stable
#HTTPD_SERVER=nginx-mainline

###
### 1.2 Choose MySQL Server Image
###
#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
MYSQL_SERVER=mysql-5.7
#MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=mariadb-5.5
#MYSQL_SERVER=mariadb-10.0
#MYSQL_SERVER=mariadb-10.1
#MYSQL_SERVER=mariadb-10.2
#MYSQL_SERVER=mariadb-10.3

###
### 1.3 Choose PostgreSQL Server Image
###
#POSTGRES_SERVER=9.1
#POSTGRES_SERVER=9.2
#POSTGRES_SERVER=9.3
#POSTGRES_SERVER=9.4
#POSTGRES_SERVER=9.5
POSTGRES_SERVER=9.6

###
### 1.4 Choose PHP Server Image
###
#PHP_SERVER=php-fpm-5.4
#PHP_SERVER=php-fpm-5.5
#PHP_SERVER=php-fpm-5.6
PHP_SERVER=php-fpm-7.0
#PHP_SERVER=php-fpm-7.1
#PHP_SERVER=hhvm-latest


###
### 1.5 Choose Redis Server Image
###     (only for docker-compose.optional.yml)
###     $ docker-compose -f docker-compose.optional.yml up
###
#REDIS_SERVER=2.8
#REDIS_SERVER=3.0
REDIS_SERVER=3.2


###
### 1.6 Timezone for all dockers and service config files
###
TIMEZONE=Europe/Moscow



################################################################################
###
### 2. Host Mounts (Your computer)
###
################################################################################

###
### Local filesystem path to www projects.
###
HOST_PATH_TO_WWW_DOCROOTS=/home/neo/server

###
### Local filesystem path to mysql/mariadb datadir.
###
### This can be an existing mysql data directory or empty.
### If it already is a mysql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new mysql database will be
### created.
###
### Note: Inside this path, a subdirectory with the mysql|mariadb
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older mysql|mariadb server versions.
###
HOST_PATH_TO_MYSQL_DATADIR=./data/mysql

###
### Local filesystem path to postgresql datadir.
###
### This can be an existing postgresql data directory or empty.
### If it already is a postgresql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new postgresql database will be
### created.
###
### Note: Inside this path, a subdirectory with the postgresql
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older postgres server versions.
HOST_PATH_TO_POSTGRES_DATADIR=./data/pgsql



################################################################################
###
### 3. HTTP Docker Settings
###
################################################################################

###
### Expose HTTPD Port to Host
###
HOST_PORT_HTTPD=80


################################################################################
###
### 4. MySQL Docker Settings
###
################################################################################

###
### MySQL root user password
###
### If $HOST_PATH_TO_MYSQL_DATADIR already contains an existing
### mysql datadir, enter the password for the existing mysql database
###
### If $HOST_PATH_TO_MYSQL_DATADIR is empty, choose a new password that
### will be applied
###
MYSQL_ROOT_PASSWORD=

###
### Custom MySQL Runtime Settings
###
MYSQL_GENERAL_LOG=1

###
### Expose MySQL Port to Host
###
HOST_PORT_MYSQL=3306



################################################################################
###
### 5. PostgreSQL Docker Settings
###
################################################################################

###
### PostgreSQL 'root' user name (usually postgres)
###
POSTGRES_USER=postgres

###
### PostgreSQL 'root' user password
###
POSTGRES_PASSWORD=

###
### Expose MySQL Port to Host
###
HOST_PORT_POSTGRES=5432


################################################################################
###
### 6. PHP-FPM Docker Settings
###
################################################################################

###
### Xdebug
###

# Enable/Disable Xdebug
PHP_XDEBUG_ENABLE=1

# Your local port (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_PORT=9000

# Your local IP address (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_HOST=172.20.10.2
## TODO: Check if it works by automatically sending it to the broadcast address



################################################################################
###
### 7. Redis Docker Settings
###
################################################################################

###
### Expost Redis Port to Host
###
HOST_PORT_REDIS=6379
```

**Comment by fe3dback** [comment]
sorry, i forgot to copy new env-example to .env, all working normal )

**Comment by cytopia** [comment]
Always good when tickets resolve itself :-)
